Page login map et géoloc
WildCodeSchool/toulouse-0218-java-ecowild pull request #1
Opened 2018-03-28 14:04 UTC by Clairehere

2018-03-28 14:06 UTC, crocknys approved these changes
ok

2018-03-28 16:31 UTC, bastienapp requested changes
Bon courage :)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".Listactivity"></activity>
Listactivity n'est pas en PascalCase (utiliser Maj-F6 pour corriger ça partout), en plus c'est une liste de quoi ? Il faut lui donner un nom plus spécifique

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/ConnectionActivity.java
> +        final SharedPreferences sharedPrefProfil = this.getPreferences(Context.MODE_PRIVATE);
final SharedPreferences sharedPrefProfil = this.getPreferences(Context.MODE_PRIVATE);

Permet d'accéder aux sharedPreferences, tu n'as pas à le rappeler plusieurs fois, tu peux utiliser sharedPrefProfil pour récupérer le mot de passe aussi

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/ConnectionActivity.java
> +                if (i == 1) {
Ici, plutôt que d'utiliser 1 ou 2 en valeur magique, stocker ça dans des constantes, du style : 

public static int PASSWORD_HIDDEN = 1;
public static int PASSWORD_VISIBLE = 2;

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/ConnectionActivity.java
> +        String usernameCache = sharedPrefProfil.getString("username", "");
Stocker username dans une constante, du style : 
public static String CACHE_USERNAME = "username";

Idem pour "password"

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/ConnectionActivity.java
> +                    Toast.makeText(ConnectionActivity.this, "Remplissez tous les champs", Toast.LENGTH_SHORT).show();
Pas de texte en dur :)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/ConnectionActivity.java
> +                    editorProfil.putString("username", editProfil);
Réutiliser les constantes pour "username" et "password" que vous aurez créer avant

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/ForgottenPasswordActivity.java
> +                if (i == 1) {
Réutiliser les constantes que vous aurez créé dans l'autre Activity PASSWORD_HIDDEN et VISIBLE

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/MainActivity.java
> +    if(ActivityCompat.checkSelfPermission(this,Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED &&
Code mal indenté

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/MainActivity.java
> +    private void checkPosition() {
Votre méthode s'appelle checkPosition mais en fait, elle ne fait que vérifier les permissions de l'utilisateur

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/MapsActivity.java
> +    private LocationManager lm;
lm n'est pas un bon nom de variable membre : mLocation est mieux

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/MemberActivity.java
> +                    Toast.makeText(MemberActivity.this, "Remplissez tous les champs", Toast.LENGTH_SHORT).show();
Pas de texte en dur

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/MemberActivity.java
> +                if (i == 1){
Réutiliser les constantes ici

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_connection.xml
> +        android:textColor="#439DBB"
Pas de couleur en dur, utiliser le fichier color :)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_connection.xml
> +        android:background="#439DBB"
Idem pour toutes les couleurs

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_listactivity.xml
> +<LinearLayoutViewLayout xmlns:android="http://schemas.android.com/apk/res/android"
Layout à renommer quand vous aurez renommé l'Activity correspondante

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:background="#439DBB"
Toutes les couleurs doivent être dans le fichier colors.xml (à corriger partout)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/cheat"
Ne pas laisser dans l'application finale :p

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/textView_title2"
Nom d'identifiant incorrect (utiliser MAJ-F6 pour le modifier)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/editText_Compte"
Nom d'identifiant incorrect, doit être en snake_case (utiliser MAJ-F6 pour le modifier)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/editText_password"
Nom d'identifiant incorrect, doit être en snake_case (utiliser MAJ-F6 pour le modifier)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/editText_password2"
Nom d'identifiant incorrect, doit être en snake_case (utiliser MAJ-F6 pour le modifier)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/imageView_password"
Nom d'identifiant incorrect, doit être en snake_case (utiliser MAJ-F6 pour le modifier)

2018-03-28 16:31 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/imageView_password2"
Nom d'identifiant incorrect, doit être en snake_case (utiliser MAJ-F6 pour le modifier)

2018-03-29 16:05 UTC, bastienapp requested changes
Tu y es presque :dancing_men:

2018-03-29 16:05 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/ForgottenPasswordActivity.java
> +        setTitle("Modifier mot de passe");
Texte en dur :(

2018-03-29 16:05 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/ecowild/MapsActivity.java
> +        MapStyleOptions carte = MapStyleOptions.loadRawResourceStyle(MapsActivity.this, R.raw.map_style);
Pas de nom de variable en français

2018-03-29 16:05 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/text_view_Title2"
snake_case (MAJ-F6)

2018-03-29 16:05 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/edit_text_Compte"
snake_case (MAJ-F6)

2018-03-29 16:05 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/edit_text_Password2"
snake_case (MAJ-F6)

2018-03-29 16:05 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/image_view_Password"
snake_case (MAJ-F6)

2018-03-29 16:05 UTC, bastienwcs commented on app/src/main/res/layout/activity_member.xml
> +        android:id="@+id/image_view_Password2"
snake_case (MAJ-F6)

2018-03-30 09:50 UTC, bastienapp approved these changes

2018-03-30 09:50 UTC, merged